---
- name: vm update
  hosts:
    - vms
  tasks:
    - name: install
      include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: server-update

- name: vm install
  hosts:
    - vms
  tasks:
    - name: install
      include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: server-install-essentials