---
- name: start-services
  hosts:
    - selected
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-{{ item }}
      loop:
        - traefik
        - registry
        - regui
        - keycloak
        - portainer
        - nexus
        - prometheus
        - grafana-agent
        - grafana
        - grafana-enterprise
        - grafana-alpha
        - loki
        - promtail
        - kafka
        - artemis
        - postgres
        - adminer
      loop_control:
        loop_var: rolesvar
