---
- name: start-services
  hosts:
    - selected
  vars:
    appstate: absent
    recreate: false
    purge: true
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-{{ item }}
      loop:
        # - traefik
        # - registry
        # - regui
        # - keycloak
        # - portainer
        # - nexus
        # - prometheus
        # - grafana-agent
        # - grafana
        # - grafana-enterprise
        - loki
        # - promtail
        # - kafka
        # - artemis
        # - postgres
        # - adminer