---

# - name: traefik
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-traefik

# - name: registry
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-registry

# - name: regui
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-regui

# - name: portainer
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-portainer

# - name: nexus
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-nexus


# - name: prometheus
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-prometheus

# - name: loki
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-loki

- name: grafana
  hosts:
    - work.lan
  vars:
    appstate: started
    recreate: true
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-grafana

- name: grafana-enterprise
  hosts:
    - work.lan
  vars:
    appstate: started
    recreate: true
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-grafana-enterprise



# - name: kafka
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-kafka

# - name: artemis
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-artemis

# - name: postgres
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-postgres

# - name: adminer
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-adminer

# - name: keycloak
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-keycloak


# - name: promtail
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: true
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-promtail


# - name: grafana-agent
#   hosts:
#     - work.lan
#   vars:
#     appstate: started
#     recreate: false
#   tasks:
#     - include_role:
#         name: cloud-native-appdev-lab-role
#         tasks_from: app-grafana-agent