---

- name: traefik
  hosts:
    - selected
  vars:
    appstate: started
    recreate: true
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-traefik

- name: portainer
  hosts:
    - selected
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-portainer


- name: kafka
  hosts:
    - selected
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-kafka

- name: artemis
  hosts:
    - selected
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-artemis

- name: postgres
  hosts:
    - selected
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-postgres

- name: adminer
  hosts:
    - selected
  vars:
    appstate: started
    recreate: false
  tasks:
    - include_role:
        name: cloud-native-appdev-lab-role
        tasks_from: app-adminer

